[workspace]
authors = ["Tuatini <email@tuatini.me>"]
channels = ["conda-forge"]
name = "lerobot"
platforms = ["osx-arm64"]
version = "0.1.0"

[dependencies]
cmake = ">=4.0.1,<5"
datasets = ">=3.5.0,<4"
deepdiff = ">=8.4.2,<9"
diffusers = ">=0.33.1,<0.34"
einops = ">=0.8.1,<0.9"
flask = ">=3.1.0,<4"
gdown = ">=5.2.0,<6"
gymnasium = "=0.29.1"
h5py = ">=3.13.0,<4"
imageio = ">=2.37.0,<3"
imageio-ffmpeg = ">=0.6.0,<0.7"
jsonlines = ">=4.0.0,<5"
numba = ">=0.61.2,<0.62"
omegaconf = ">=2.3.0,<3"
opencv = ">=4.11.0,<5"
packaging = ">=24.2,<25"
av = ">=14.2.0,<15"
pymunk = ">=6.10.0,<7"
pynput = ">=1.8.1,<2"
pyzmq = ">=26.4.0,<27"
rerun-sdk = ">=0.22.1,<0.23"
termcolor = ">=3.0.1,<4"
pytorch = ">=2.6.0,<3"
torchcodec = ">=0.2.1,<0.3"
torchvision = ">=0.21.0,<0.22"
wandb = ">=0.19.9,<0.20"
zarr = ">=3.0.6,<4"

[pypi-dependencies]
gymnasium = "*"
huggingface-hub = { version = "*", extras = ["hf-transfer", "cli"] }
lerobot = { path = ".", editable = true, extras = ["feetech"] }

