robot:
  type: so100
  calibration_dir: $PROJECT_DIR/.cache/calibration/so100/
  # TODO: Replace device discovery with udev rules
  leader_arms:
    main:
      device: /dev/ttyACM0
  follower_arms:
    main:
      device: /dev/ttyACM1
  cameras:
    # This camera is a Droidcam app running on the smartphone
    front:
      type: ip_camera
      # IP address given by DroidCam app on the smartphone
      vcam_ip: 100.75.155.120
      vcam_port: 4747
      fps: 30
      width: 640
      height: 480
      rotation: 90
    wrist:
      type: opencv
      # Wrist camera
      device: /dev/video5
      fps: 30
      width: 640
      height: 480
      rotation: 180

dataset_recording:
  repo_id: Ekami/so100
  fps: 30
  tags:
    - so100
    - Stack bricks
  episode_time_s: 30

