rerun:
  viewer_ip: 100.110.81.39 # Macbook air IP
  viewer_port: 9876

robot:
  type: so100
  calibration_dir: ~/.cache/calibration/so100/
  leader_arms:
    main:
      device: /dev/ttyACM0
  follower_arms:
    main:
      device: /dev/ttyACM1
  cameras:
    # This camera is a Droidcam app running on the smartphone
    front:
      type: ip_camera
      # On what device the smartphone camera will map to
      device: /dev/video0
      # IP address given by DroidCam app on the smartphone
      vcam_ip: 100.75.155.120
      vcam_port: 4747
      fps: 30
      width: 640
      height: 480
      rotation: 90
    wrist:
      type: opencv
      # Wrist camera
      device: /dev/video5
      fps: 30
      width: 640
      height: 480
      rotation: 180